[package]
name = "fracks-token-hook"
version = "0.1.0"
description = "FRACKS Token-2022 transfer-hook enforcement program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "fracks_token_hook"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
solana-program = { workspace = true }
fracks-compliance = { path = "../fracks-compliance", features = ["cpi"] }
spl-transfer-hook-interface = "0.10.0"
spl-tlv-account-resolution = "0.10.0"
