[package]
name = "fracks-irs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "fracks_irs"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "fracks-fid/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
fracks-fid = { path = "../fracks-fid", features = ["cpi"] }
